import { BottomTabsItem } from './BottomTabsItem';

export const BottomTabsList: Array<BottomTabsItem> = [
  {
    icon: $r('app.media.bottom1'),
    iconSelected: $r('app.media.bottom1selected'),
    text: $r('app.string.bottom_text_map')
  },
  {
    icon: $r('app.media.bottom2'),
    iconSelected: $r('app.media.bottom2selected'),
    text: $r('app.string.bottom_text_zones')
  },
  {
    icon: $r('app.media.bottom2'),
    iconSelected: $r('app.media.bottom2selected'),
    text: $r('app.string.bottom_text_zones1')
  },
  {
    icon: $r('app.media.bottom3'),
    iconSelected: $r('app.media.bottom3selected'),
    text: $r('app.string.bottom_text_trains')
  },

  {
    icon: $r('app.media.bottom4'),
    iconSelected: $r('app.media.bottom4selected'),
    text: $r('app.string.bottom_text_trains1')
  }
]